FROM couchbase
COPY tests/Docker/build-couchbase.sh /opt/couchbase/build-couchbase.sh
HEALTHCHECK --interval=5s --timeout=3s CMD curl --fail http://localhost:8091/pools || exit 1
CMD ["/opt/couchbase/build-couchbase.sh"]
